New function. Dstat on load alert
New INTERACTIVE function to see if we are in an interactive shell.
Prompts to run dstat if the load warning appears if INTERACTIVE returns 0
Version change

diff --git a/where b/where
--- a/where
+++ b/where
@@ -42,18 +42,17 @@ set -u
 #VERSION=1.11.4 # CR # 11/08/2016 # Replaced the tr for a sed in the network DEV interface names. Caters for Bonding and interfaces with multiple addresses.
 #VERSION=1.11.5 # CR # 07/03/2017 # Found a working link for dstat, as well as his github. Using the tar file for the time being.
  VERSION=1.11.6 # CR # 07/03/2017 # Replaced "wget -q -O -" with curl for downloading dstat 
+ VERSION=1.12.0 # CR # 09/06/2017 # Removes environment specific entries and prompts to run dstat if the load warning appears if shell is interactive (new INTERACTIVE function)
 
 shopt -s -o errexit #nounset
 #shopt -s -o errexit nounset
 
-##ToDo:
-#Add -a --all to run all functions.
-#Add Function SHOW_USED_SPACE showing what is taking up the most space.
-#Have SHOW_USED_SPACE called automatically when used space is above 90% or 95%
-#Detect large listener logs $ORACLE_HOME/diag/tnslsnr/SITECODE/listener/trace/listener.log
-#Have DSTAT called automatically when LOAD is above 2.0
-#Fix up declarations!!!
-#Remove ACR Specific entries...
+## ToDo:
+# Add -a --all to run all functions ?
+# Add Function SHOW_USED_SPACE showing what is taking up the most space.
+# Have SHOW_USED_SPACE called automatically when used space is above 90% or 95%
+# Detect large listener logs $ORACLE_HOME/diag/tnslsnr/SITECODE/listener/trace/listener.log
+# Fix up declarations!!!
 
 ##Vars
 declare -r TODAY=`date +%Y-%m-%d`
@@ -64,7 +63,7 @@ declare TNSNAMES
 if [ -n ${ORACLE_HOME:-} ]; then
   [ -f "${ORACLE_HOME:-}/network/admin/tnsnames.ora" ] && TNSNAMES="${ORACLE_HOME}/network/admin/tnsnames.ora";
 elif [ -f "$ORACLE_HOME/tnsnames.ora" ]; then
-  TNSNAMES="$ORACLE_HOME/tnsnames.ora"; #This one caters for saas-app1
+  TNSNAMES="$ORACLE_HOME/tnsnames.ora"
 fi
 
 declare -r HEADING="Partition\tFull\tFree\tSize\tType
@@ -82,6 +81,14 @@ declare -r REDBLACK="\033[41;30m"
 #BLINK="\e[5m"
 
 ##Functions
+
+function INTERACTIVE(){
+  case "$-" in
+    *i*)	return 0 ;;
+    *)	return 1 ;;
+  esac
+
+}
 
 function CORES(){
 
@@ -326,6 +333,7 @@ function SYSTEMLOAD(){
   local -i ONE_CHECK=`echo "${ONE}"|cut -d. -f1`
   local -i FIVE_CHECK=`echo "${FIVE}"|cut -d. -f1`
   local -i FIFTEEN_CHECK=`echo "${FIFTEEN}"|cut -d. -f1`
+  local ANS
   #Setting colors
   SHOW="no"
 
@@ -343,7 +351,12 @@ function SYSTEMLOAD(){
 
   [ "$SHOW" = yes -o "$SYSTEMLOAD_ARG" = all ] && \
   echo -e "System Load \n1min\t5min\t15min \n${ONE}\t${FIVE}\t${FIFTEEN}"
-  return 0
+  INTERACTIVE && echo "Run dstat? [Y/n]"
+  read ANS
+  [ "$ANS" = "N" -o "$ANS" = "n" ] || DSTAT
+  #[ $ONE_CHECK -gt 1 ] && DSTAT
+
+  return $?
 }
 
 function MAILQUEUE(){
@@ -358,25 +371,25 @@ function MAILQUEUE(){
       local LIST=`find $MQUEUE -type f`
       local GOINGTO=`grep To:.*@ $MQUEUE/Qf* 2>/dev/null | cut -d" " -f2 | sed -e 's/<//g' -e 's/>//g' | sort | tr [:upper:] [:lower:] | uniq -c | sort -nr`
       local GOINGTO_COUNT=`echo "$GOINGTO" | grep @ | wc -l`
-#      COMINGFROM=`grep From:.* $MQUEUE/Qf* 2>/dev/null | cut -d: -f3`
-#      TO_FROM_LIST="/tmp/tfl"
-#      rm $TO_FROM_LIST 2>/dev/null
-#      if [ -n "$LIST" ]; then
-#        echo "$LIST" | grep "$MQUEUE/Qf" | \
-#        while read EMAIL; do
-#          #TO=`grep To:.*@ $EMAIL 2>/dev/null | cut -d" " -f2 | sed -e 's/<//g' -e 's/>//g' | sort -u | tr [:upper:] [:lower:]`
-#          TO=`grep To:.*@ $EMAIL 2>/dev/null | cut -d" " -f2 | head -1 | sed -e 's/<//g' -e 's/>//g'`
-#          FROM=`grep -e From:.*@ -e "Mail Delivery Subsystem" $EMAIL 2>/dev/null | cut -d" " -f2- | head -1 | sed -e 's/<//g' -e 's/>//g'`
-#          [ -n "${TO}" -a -z "${FROM}" ] && echo -e "${TO}\t\t\t${EMAIL:18}" >>"$TO_FROM_LIST"
-#          [ -z "${TO}" -a -n "${FROM}" ] && echo -e "\t\t\t${FROM}\t${EMAIL:18}" >>"$TO_FROM_LIST"
-#          [ -n "${TO}" -a -n "${FROM}" ] && echo -e "${TO}\t${FROM}\t${EMAIL:18}" >>"$TO_FROM_LIST"
-#          #[ "$TO" -a -z "$FROM" ] && echo && echo "$EMAIL" && echo -e "To:${TO}"
-#          #[ "$TO" -a "$FROM" ] && echo && echo "$EMAIL" && echo -e "To:${TO}\t\tFrom:${FROM}"
-#        done
-#        cat "$TO_FROM_LIST" | sort -s -n -k 1,1
-#      fi
-#      exit
-      #Getting the age of the failed emails -- START
+      #COMINGFROM=`grep From:.* $MQUEUE/Qf* 2>/dev/null | cut -d: -f3`
+      #TO_FROM_LIST="/tmp/tfl"
+      #rm $TO_FROM_LIST 2>/dev/null
+      #if [ -n "$LIST" ]; then
+      #  echo "$LIST" | grep "$MQUEUE/Qf" | \
+      #  while read EMAIL; do
+      #    #TO=`grep To:.*@ $EMAIL 2>/dev/null | cut -d" " -f2 | sed -e 's/<//g' -e 's/>//g' | sort -u | tr [:upper:] [:lower:]`
+      #    TO=`grep To:.*@ $EMAIL 2>/dev/null | cut -d" " -f2 | head -1 | sed -e 's/<//g' -e 's/>//g'`
+      #    FROM=`grep -e From:.*@ -e "Mail Delivery Subsystem" $EMAIL 2>/dev/null | cut -d" " -f2- | head -1 | sed -e 's/<//g' -e 's/>//g'`
+      #    [ -n "${TO}" -a -z "${FROM}" ] && echo -e "${TO}\t\t\t${EMAIL:18}" >>"$TO_FROM_LIST"
+      #    [ -z "${TO}" -a -n "${FROM}" ] && echo -e "\t\t\t${FROM}\t${EMAIL:18}" >>"$TO_FROM_LIST"
+      #    [ -n "${TO}" -a -n "${FROM}" ] && echo -e "${TO}\t${FROM}\t${EMAIL:18}" >>"$TO_FROM_LIST"
+      #    #[ "$TO" -a -z "$FROM" ] && echo && echo "$EMAIL" && echo -e "To:${TO}"
+      #    #[ "$TO" -a "$FROM" ] && echo && echo "$EMAIL" && echo -e "To:${TO}\t\tFrom:${FROM}"
+      #  done
+      #  cat "$TO_FROM_LIST" | sort -s -n -k 1,1
+      #fi
+      #exit
+      # Getting the age of the failed emails -- START
       local SECONDS=`date +%s`
       local O_EMAIL_FILE=`ls -tr $MQUEUE/Qf* 2>/dev/null | head -1`
       local N_EMAIL_FILE=`ls -t  $MQUEUE/Qf* 2>/dev/null | head -1`
@@ -390,7 +403,7 @@ function MAILQUEUE(){
         local O_MSG="The oldest failed email is ${O_EMAIL} Days old"
         local N_MSG="The newest failed email is ${N_EMAIL} Days old"
       fi
-      #Getting the age of the failed emails -- STOP
+      # Getting the age of the failed emails -- STOP
 
       if [ "$GOINGTO_COUNT" -gt 0 -a "$MAILQUEUE_ARG" != all -a -n "$TOTAL_FAILED_EMAILS" ]; then
         echo "$TOTAL_FAILED_EMAILS dead email(s) with $GOINGTO_COUNT unique email addresses."
